api:
  auth:
    verifySSL: false
    basic:
      user: some.guy@profitbricks.com
      password: secret
  url: https://api.profitbricks.com/cloudapi/v4
  wait:
    factor: 1.87
    init:
      milliseconds: 2000
    max:
      milliseconds: 5000
    timeout:
      seconds: 360
  verbose: true

